# Generated by Django 4.1.2 on 2022-11-11 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_alter_task_author_alter_task_doer_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="doer",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="DoerTitle",
            ),
            preserve_default=False,
        ),
    ]
