# Generated by Django 4.1.2 on 2022-11-12 08:14

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tasks", "0010_alter_task_doer"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullNamedUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.fullnameduser",
                verbose_name="AuthorTitle",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="doer",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tasks.fullnameduser",
                verbose_name="DoerTitle",
            ),
        ),
    ]
