# Generated by Django 4.1.2 on 2022-11-14 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_alter_status_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0011_alter_task_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="doer",
        ),
        migrations.AddField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Creation date"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="statuses.status",
                verbose_name="Status",
            ),
        ),
    ]
