# Generated by Django 4.1.2 on 2022-11-13 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
        ("tasks", "0011_alter_task_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="tags.tag", verbose_name="TagsTitle"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="doer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="DoerTitle",
            ),
        ),
    ]
