# Generated by Django 4.1.2 on 2022-11-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks",
            "0012_remove_task_doer_task_executor_alter_task_author_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Name"
            ),
        ),
    ]
