# Generated by Django 4.1.2 on 2022-11-13 12:47

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    TaskTags = apps.get_model('tasks', 'TaskTags')
    for task in Task.objects.all():
        for tag in task.tags.all():
            TaskTags(
                task=task,
                tag=tag
            ).save()

class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_alter_task_tags_tasktags"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
