# Generated by Django 4.1.2 on 2022-11-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("tasks", "0014_auto_20221113_1247"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
    ]
