# Generated by Django 4.1.2 on 2022-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("tasks", "0015_remove_task_tags_tasktags"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                through="tasks.TaskTags",
                to="tags.tag",
                verbose_name="TagsTitle",
            ),
        ),
    ]
