# Generated by Django 4.1.2 on 2022-11-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0015_task_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "labels",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="labels.label",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
