# Generated by Django 4.1.2 on 2022-11-14 17:21

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    TaskLabels = apps.get_model('tasks', 'TaskLabels')
    for task in Task.objects.all():
        for label in task.labels.all():
            TaskLabels(
                task=task,
                label=label
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_tasklabels"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
