# Generated by Django 4.1.2 on 2022-11-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name_plural": "Statuses"},
        ),
    ]
