# Generated by Django 4.1.2 on 2022-11-14 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_alter_status_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="creation_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Creation date"
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Name"
            ),
        ),
    ]
